### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by SorenHolstHansen**
@AlecAivazis  I thought I would make a docs page for Houdini. So i have made an initial setup with svelte-kit and mdsvex.

However before I do too much styling and such, I thought you could have a look and see, and say what you like and don't like so we can get it in the right direction.

### CODE REVIEW

**Comment by AlecAivazis** [comment]
whoa!! thanks so much for this! I'll try to find some time this week to pull this down and go through it

**Comment by AlecAivazis** [comment]
@SorenHolstHansen i added you as a maintainer on [a repo](https://github.com/houdinigraphql/docs) in a new [houdini organization](https://github.com/houdinigraphql) on github. Mind opening a PR there so we don't clutter the main repository too much?

**Comment by SorenHolstHansen** [comment]
Cool! I accidentally pushed the branch first, so now that is the default branch, and i can't change that...

**Comment by AlecAivazis** [comment]
ah damn, okay i went ahead and deleted the repo so we can start fresh. It's probably worth mentioning that only the `docs` package should be on that repo, not the full houdini source. That will eventually end up in the org too

**Comment by SorenHolstHansen** [comment]
@AlecAivazis Can you make a new repo, so I can make a pull request?

**Comment by AlecAivazis** [comment]
Oh sorry! It was created as a private repo for some reason, its been fixed now

**Comment by AlecAivazis** [comment]
let's start off with a PR just to review the actual submission and i'll add your perms after, its a busy day for me so i might not get to it til later

**Comment by SorenHolstHansen** [comment]
I can't do that either since the repository is empty, it complaints that it is not a repo

**Comment by SorenHolstHansen** [comment]
But no worries, we will just figure it out when you get the time

**Comment by AlecAivazis** [comment]
Ah, damn! Okay it should have a readme now

**Comment by SorenHolstHansen** [comment]
Great, I have made a PR now

**Comment by AlecAivazis** [comment]
Going to close this since we're moving it over to the other repo

**Pull request closed without merging**
