### PR TITLE
fix houdini not working with sveltekit-flash-messages

### LINKED ISSUE #1137: Cannot use it alongside sveltekit-flash-message
### Describe the bug

I'm trying to build a demo application featuring Houdini in SvelteKit and i ran into this issue:

> If i wrap the loadFlash function around load i end up with two load functions and breaks the app. Removing it makes it run but i need flash messages.

`Internal server error: Transform failed with 2 errors:
/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts:14:13: ERROR: Multiple exports with the same name "load"
/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts:14:13: ERROR: The symbol "load" has already been declared
  Plugin: vite:esbuild
  File: /home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts:14:13

  Multiple exports with the same name "load"
  12 |  }
  13 |
  14 |  export const load = loadFlash(async (
     |               ^
  15 |      {
  16 |          locals

  The symbol "load" has already been declared
  12 |  }
  13 |
  14 |  export const load = loadFlash(async (
     |               ^
  15 |      {
  16 |          locals

      at failureErrorWithLog (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:1649:15)
      at /home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:847:29
      at responseCallbacks.<computed> (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:703:9)
      at handleIncomingPacket (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:762:9)
      at Socket.readFromStdout (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:679:7)
      at Socket.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) (x4)
Error: Transform failed with 2 errors:
/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts:14:13: ERROR: Multiple exports with the same name "load"
/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts:14:13: ERROR: The symbol "load" has already been declared
    at failureErrorWithLog (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:1649:15)
    at /home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:847:29
    at responseCallbacks.<computed> (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/home/kloon/Projects/andrescraper-svelte/node_modules/vite/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Multiple exports with the same name "load"'
    },
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'The symbol "load" has already been declared'
    }
  ],
  warnings: [],
  frame: '\n' +
    '\x1B[33mMultiple exports with the same name "load"\x1B[39m\n' +
    '12 |  }\n' +
    '13 |  \n' +
    '14 |  export const load = loadFlash(async (\n' +
    '   |               ^\n' +
    '15 |      {\n' +
    '16 |          locals\n' +
    '\n' +
    '\x1B[33mThe symbol "load" has already been declared\x1B[39m\n' +
    '12 |  }\n' +
    '13 |  \n' +
    '14 |  export const load = loadFlash(async (\n' +
    '   |               ^\n' +
    '15 |      {\n' +
    '16 |          locals\n',
  loc: {
    column: 13,
    file: '/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts',
    length: 4,
    line: 14,
    lineText: 'export const load = loadFlash(async (',
    namespace: '',
    suggestion: ''
  },
  plugin: 'vite:esbuild',
  id: '/home/kloon/Projects/andrescraper-svelte/src/routes/+layout.server.ts',
  pluginCode: 'import { buildSessionObject } from "$houdini/plugins/houdini-svelte/runtime/session";\n' +
    'import type { LayoutServerLoad } from "./$types";\n' +
    'import { loadFlash } from "sveltekit-flash-message/server";\n' +
    '\n' +
    'export async function load(event) {\n' +
    '    const __houdini__vite__plugin__return__value__ = {};\n' +
    '\n' +
    '    return {\n' +
    '        ...buildSessionObject(event),\n' +
    '        ...__houdini__vite__plugin__return__value__\n' +
    '    };\n' +
    '}\n' +
    '\n' +
    'export const load = loadFlash(async (\n' +
    '    {\n' +
    '        locals\n' +
    '    }\n' +
    ') => {\n' +
    '    return {\n' +
    '        user: locals.user\n' +
    '    };\n' +
    '}) satisfies LayoutServerLoad;'
}`

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

1. Have a basic load function in the global +layout.server.ts file:
```
import type { LayoutServerLoad } from './$types'
import { loadFlash } from 'sveltekit-flash-message/server'

export const load = (async ({ locals }) => {
  return {
    user: locals.user,
  }
}) satisfies LayoutServerLoad

```
2. Wrap it in loadFlash()
3. Fails with `Multiple exports with the same name "load"`

### Reproduction

_No response_

### PR DESCRIPTION
**Pull request by eikaramba**
When we have 
`export const load = loadFlash(async ({ locals,fetch}) => {`

the actual AST of the init function looks like this inside the variableDeclaration:
```
Node3 {
  type: 'CallExpression',
  start: 179,
  end: 797,
  loc: SourceLocation3 {
    start: Position3 { line: 5, column: 20, index: 179 },
    end: Position3 { line: 25, column: 2, index: 797 },
    filename: undefined,
    identifierName: undefined
  },
  callee: Node3 {
    type: 'Identifier',
    start: 179,
    end: 188,
    loc: SourceLocation3 {
      start: [Position3],
      end: [Position3],
      filename: undefined,
      identifierName: 'loadFlash'
    },
    name: 'loadFlash'
  },
  arguments: [
    Node3 {
      type: 'FunctionExpression',
      start: 189,
      end: 796,
      loc: [SourceLocation3],
      id: [Node3],
      generator: false,
      async: true,
      params: [Array],
      body: [Node3]
    }
  ]
}
```

Here we see that the argument has the load function we are trying to patch

Fixes #1137

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [ ] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [ ] Includes a changeset if your fix affects the user with `pnpm changeset`

### CODE REVIEW

**Comment by AlecAivazis** [comment]
Thanks for hunting this down! Do you mind adding a test in [this file](https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/plugin/transforms/kit/load.test.ts#L145)?

**Comment by eikaramba** [comment]
@AlecAivazis unfortunately the tests are always throwing an error on my machine (windows maybe?). some 

```
#FailureMessage Object: 0000001DA32FE0B0
 1: 00007FF7E8537C4F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114207
 2: 00007FF7E8453CCF std::basic_ostream<char,std::char_traits<char> >::operator<<+65103
 3: 00007FF7E9132CE2 V8_Fatal+162
 4: 00007FF7E8B9DF1D v8::internal::BackingStore::Reallocate+637
 5: 00007FF7E8DE7699 v8::ArrayBuffer::GetBackingStore+137
```

anway i started this in the sessions file, which i think is the better place but honestly i have no idea what i am doing and thus i wasn't able to write the correct expected output. can you adapt that?
https://github.com/HoudiniGraphql/houdini/blob/main/packages/houdini-svelte/src/plugin/transforms/kit/session.test.ts#L63


```js
test("modifies existing load +layout.server.js with a callexpression wrapper", async function () {
	const result = await test_transform_js(
		'src/routes/+layout.server.js',
		`
				function wrapper(cb){
					return async (event) => { 
						const loadFunction = await cb(event); 
						return { ...loadFunction }; 
					  }; 
				})
				export const load = wrapper(async (event)=>{

				})
			`
	)

	expect(result).toMatchInlineSnapshot(`
		import { buildSessionObject } from "$houdini/plugins/houdini-svelte/runtime/session";

		export async function load(event) {
			"FIX THIS CODE!!!";
			const __houdini__vite__plugin__return__value__ = {};

			return {
				...buildSessionObject(event),
				...__houdini__vite__plugin__return__value__
			};
		}
	`)
})
```

**Comment by eikaramba** [comment]
ah and i forgot to run the linter, i am sorry.

**Comment by AlecAivazis** [comment]
Whoa not sure what's causing that but no problem! I can take it from here 👍

**Review by AlecAivazis — APPROVED** [review]

**Pull request merged**
