### PR TITLE
move some things to the multipart context

### PR DESCRIPTION
**Pull request by 524c**
### To help everyone out, please make sure your PR does the following:

- [ ] Update the first line to point to the ticket that this PR fixes
- [ ] Add a message that clearly describes the fix
- [ ] If applicable, add a test that would fail without this fix
- [ ] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [ ] Includes a changeset if your fix affects the user with `pnpm changeset`

### CODE REVIEW

**Review by AlecAivazis — APPROVED** [review]
Simple enough! Nice catch 👍

**Comment by AlecAivazis** [comment]
For some reason the upload e2e test is super unstable in windows 🤔

**Comment by 524c** [comment]
> For some reason the upload e2e test is super unstable in windows 🤔

I can't see it. Did you test manually? 🧐

**Comment by sjcobb2022** [comment]
> For some reason the upload e2e test is super unstable in windows 🤔 

From my experience both the playwright CDNs servers can be slow and sometimes timeout + the GitHub actions windows machines generally struggle running them.

**Comment by 524c** [comment]
> For some reason the upload e2e test is super unstable in windows 🤔

I've noticed that tests are slower on Windows, but it seems to me that it affects all tests in general, or not? I don't have a Windows workstation here, otherwise I would do a test manually.

**Pull request merged**
