### PR TITLE
Support '.graphqls' file extension

### LINKED ISSUE #1381: Support '*.graphqls' files in tooling
### Describe the feature

In some codebases, the file extension `.graphqls` distinguishes the GraphQL schema from other GraphQL files. Currently, Houdini wrongly assumes files ending in `.graphqls` are JSON files, resulting in weird error messages. Having this extension supported would be really nice.

### Criticality

cool improvement, my projects will benefit from it

### PR DESCRIPTION
**Pull request by gschulze**
Fixes #1381 

Adds support for `*.graphqls` files in tooling.

### CODE REVIEW

**Review by AlecAivazis — APPROVED** [review]
Easy enough. Nice!

**Comment by gschulze** [comment]
> Oh, i just realized we'll need a changeset file. Mind adding one quickly so I can merge this?

I've never worked with changesets before, otherwise I'd have done it already. Where do I need to put it?

**Comment by SeppahBaws** [comment]
> > Oh, i just realized we'll need a changeset file. Mind adding one quickly so I can merge this?
> 
> I've never worked with changesets before, otherwise I'd have done it already. Where do I need to put it?

Just run `pnpm changeset` in the repo and walk through the steps for adding a patch change

**Comment by gschulze** [comment]
@AlecAivazis I added the changeset - I assume it's a patch. Would be nice if we could have a release of this change soon :)

**Comment by SeppahBaws** [comment]
Looks like you just need to run the prettier script for formatting, and then we can merge this 🙂

**Comment by gschulze** [comment]
> Looks like you just need to run the prettier script for formatting, and then we can merge this 🙂

Done.

**Review by SeppahBaws — APPROVED** [review]
Awesome, thanks for adding this!

**Pull request merged**
